version: 2
jobs:
  generate_and_test:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      - restore_cache:
          key: -V2-cc_tuts
      - run:
          name: Get single_source 
          command: nix-shell https://holochain.love --run 'cargo install single_source' 
      - run:
          name: Pass through
          command: ./create_docs.sh
      - run:
          name: Run all tests
          command: nix-shell https://holochain.love --run './run_all_tests.sh' 
      - save_cache:
          key: -V2-cc_tuts
          paths:
            - "cc_tuts"
      - persist_to_workspace:
          root: .
          paths:
            - docs/*
            - build/docs/*

  build-mkdocs:
    docker:
      - image: squidfunk/mkdocs-material

    steps:
      - checkout
      - attach_workspace:
          at: . 
      - run:
          name: Build mkdocs 
          command: mkdocs build -d build/docs
      - persist_to_workspace:
          root: .
          paths:
            - docs/*
            - build/*
   
  release:
    docker:
          - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: . 
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Netlify Deploy
          command: netlify deploy --prod --dir=build
          no_output_timeout: 300m

workflows:
  version: 2
  build_and_test:
    jobs:
      - generate_and_test:
          filters:
            branches:
              only: 
                - develop
                - master
#      - build-mkdocs:
#          requires:
#            - generate_and_test
#          filters:
#            branches:
#              only: master
#      - release:
#          requires:
#            - build-mkdocs
#            - generate_and_test
#          filters:
#            branches:
#              only: master 
